name: phoenix
services:
  main:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    hostname: phoenix
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    volumes:
      - ..:/home/user/workspace
